# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=False),
        ),
    ]
